
import { Inter } from 'next/font/google'
import './globals.css'
import { AuthContextProvider } from './utils/AuthWrapper'
import { SocketContextProvider } from './utils/SocketWrapper'
import Providers from './redux/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Providers>
            <SocketContextProvider>
              {children}
            </SocketContextProvider>
          </Providers>
        </AuthContextProvider>
      </body>
    </html>
  )
}
